### ISSUE TITLE
config/database.php

### ISSUE THREAD

**Issue by akmetin** [jooorooo/installer#1]
Hey,
I guess would be better if only add/changes variables on .env file. Not useful to edit config/database.php.
Thanks for package.

**Comment by deepnees** [comment]
Sorry I just realize this topic should be in pull requests. my mistake
Also I have a question about migrations.
What should I type in installer.php  'migrations' => '', for run specific migration file on updates.
Thanks

**Comment by jooorooo** [comment]
In release 1.6.4 configuration data is writen to .env file.
